#!/usr/bin/env python3
"""Draws from the Tabeli their MACHINE-READABLE versions.

WHY. The page weighs 3.3 MB for 257 kB of text: thirteen bytes of markup
for one of text. The table carries 683 entries in 57 languages, and it is
precisely its richness that makes it illegible to a machine -- the 53
languages other than Ido and French are EMPTY cells which the browser then
fills from lingui/*.json.

THE POINT THAT COUNTS: the rows' keys (data-cle) are EXACTLY those of the
language files. Publishing the Ido/French pairs under those same keys
therefore makes the whole corpus joinable by program: whoever wants the
Ido-Japanese pair joins tabeli.json and lingui/ja.json on the key, without
having to open the page or run its JavaScript.

  tabeli.json       {key: {io, fr}} — the hinge of the corpus.
  tabeli.md         the table laid flat, Ido and French facing.
  lingui/index.json the 57 languages offered, with their code and weight.

Generated, never edited by hand. The source stays index.html.

    python3 tools/machine_readable.py
"""

import json
import os
import re
import sys
from pathlib import Path

# This directory carries its own "html.py", which would shadow the standard module.
sys.path[:] = [d for d in sys.path
               if os.path.abspath(d) != os.path.dirname(os.path.abspath(__file__))]
import html as modul_html  # noqa: E402
from html.parser import HTMLParser  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
HEADER = ('<!-- Generated by tools/machine_readable.py from index.html. '
          'Do not edit. -->\n')
SOURCE = 'Transskribita de https://ido.help/tabeli/\n'


def text_(h: str) -> str:
    """A fragment of HTML as plain text.

    The "ln" are LINES of the printed book, not sentences: the original
    table is set in narrow columns, and a sentence there runs over three or
    four lines. We rejoin them with a space, failing which the text
    rendered would be chopped where the book is not -- an artefact of
    layout, not of the text.
    """
    h = re.sub(r'<span class="fil"></span>', '', h)
    h = re.sub(r'<i>(.*?)</i>', r'*\1*', h, flags=re.S)
    h = re.sub(r'<b>(.*?)</b>', r'**\1**', h, flags=re.S)
    h = re.sub(r'<[^>]+>', ' ', h)
    h = modul_html.unescape(h)
    return re.sub(r'\s+', ' ', h).strip()


class Rows(HTMLParser):
    """Gathers the table's rows, and for each of them the Ido and the French.

    We count the depth rather than looking for the closing "/div": a cell
    contains "span"s, and sometimes other "div"s.
    """

    def __init__(self):
        super().__init__(convert_charrefs=False)
        self.rows, self.current_state, self.depth = [], None, 0
        self.target_, self.pieces_ = None, []

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        kl = (a.get('class') or '').split()
        if self.current_state is None:
            if tag == 'div' and 'r' in kl and a.get('data-cle'):
                self.current_state = {'cle': a['data-cle'],
                             'speco': next((k for k in kl if k != 'r'), ''),
                             'io': '', 'fr': ''}
                self.depth = 1
            return
        if tag == 'div':
            self.depth += 1
            if 'k' in kl and 'vaka' not in kl:
                self.target_ = 'io' if 'io' in kl else (
                    'fr' if a.get('data-lg') == 'fr' else None)
                self.pieces_ = []
                return
        if self.target_:
            self.pieces_.append(self.get_starttag_text() or '')

    def handle_endtag(self, tag):
        if self.current_state is None:
            return
        if tag == 'div':
            self.depth -= 1
            if self.target_ and self.depth >= 1:
                self.current_state[self.target_] = text_(''.join(self.pieces_))
                self.target_ = None
                return
            if self.depth == 0:
                self.rows.append(self.current_state)
                self.current_state = None
                return
        if self.target_:
            self.pieces_.append('</%s>' % tag)

    def handle_data(self, d):
        if self.target_:
            self.pieces_.append(d)

    def handle_entityref(self, n):
        if self.target_:
            self.pieces_.append('&%s;' % n)

    def handle_charref(self, n):
        if self.target_:
            self.pieces_.append('&#%s;' % n)


def hand() -> None:
    s = (ROOT / 'index.html').read_text(encoding='utf-8')
    body_m = re.search(r'<main\b.*?</main>', s, re.S)
    p = Rows()
    p.feed(body_m.group(0) if body_m else s)
    rows = [r for r in p.rows if r['io'] or r['fr']]

    # 1. The hinge of the corpus.
    (ROOT / 'tabeli.json').write_text(
        json.dumps({r['cle']: {'io': r['io'], 'fr': r['fr']} for r in rows},
                   ensure_ascii=False, separators=(',', ':')), encoding='utf-8')

    # 2. The table laid flat.
    lin = [HEADER, '# Expliko-Libreto di la Delmas-Tabeli helpanta\n',
           'J. Guignon · Ido-Kontoro, Thaon-les-Vosges, 1926 · '
           'E. Rochelle · G. Delmas, Bordeaux\n', SOURCE,
           'Ido e Franca en regardo. La 55 altra lingui esas en lingui/*.json, '
           'kun la sama klefi.\n', '---\n',
           '| klefo | Ido | Franca |', '| --- | --- | --- |']
    for r in rows:
        io = r['io'].replace('|', '\\|')
        fr = r['fr'].replace('|', '\\|')
        lin.append('| `%s` | %s | %s |' % (r['cle'], io, fr))
    (ROOT / 'tabeli.md').write_text('\n'.join(lin) + '\n', encoding='utf-8')

    # 3. The languages offered.
    langs_dir = ROOT / 'lingui'
    list_ = sorted(f.name[:-5] for f in langs_dir.glob('*.json')
                   if f.name != 'index.json')
    (langs_dir / 'index.json').write_text(json.dumps(
        {'pri': 'Lingui dil Delmas-Tabeli. La klefi esas ti di tabeli.json.',
         'fonto': 'https://ido.help/tabeli/',
         'enshaltita': {'io': 'en index.html e tabeli.json',
                        'fr': 'en index.html e tabeli.json'},
         'lingui': [{'kodexo': k,
                     'okteti': (langs_dir / (k + '.json')).stat().st_size}
                    for k in list_]},
        ensure_ascii=False, indent=1), encoding='utf-8')

    print('  %d rows' % len(rows))
    for n in ('tabeli.json', 'tabeli.md'):
        print('  %-16s %10s bytes' % (n, format((ROOT / n).stat().st_size, ',')))
    print('  lingui/index.json  %d languages' % len(list_))


if __name__ == '__main__':
    hand()
